name: Deploy staging to Heroku
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_STAGING_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}